language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install --prefer-source
  - php app/console doctrine:schema:update --env=test --force
  - php app/console wozbe:install --env=test --default
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install
  - bower install
  - grunt symlink
  - grunt  

script: phpunit -c app/

notifications:
  email:
    - thomas@tourlourat.com
