language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install --prefer-source --no-interaction
  - app/console cache:clear --env=test
  - app/console assets:install --env=test

script: phpunit -c app/

notifications:
  email:
    - thomas@tourlourat.com
