<?php

namespace Wozbe\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findPublished(array $criteria = array(), array $orderBy = null, $limit = null, $offset = null)
    {
        return $this->findBy(
                array_merge($criteria, array('published' => true)),
                $orderBy, 
                $limit, 
                $offset);
    }
    
    public function findOneBySlug($slug, array $criteria = array(), array $orderBy = null, $limit = null, $offset = null)
    {
        return $this->findOneBy(
                array_merge($criteria, array('slug' => $slug)),
                $orderBy, 
                $limit, 
                $offset);
    }
}
