imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%kernel.cache_dir%/db_test.sqlite"
        charset:  UTF8

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

services:
    wozbe_admin.manager.configuration:
        alias: wozbe_admin.manager.configuration_dummy