imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    default_locale:  "%locale%"
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: '0.1.0'
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        phone: %phone%
        email: %email%


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

wozbe_redirect:
    domains:
        wozbe.com:
            aliases:
                - www.wozbe.com
                - www.woxbe.com
                - woxbe.com

jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%/Resources/views, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            output_format: xliff
            
services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
