wozbe_admin:
    resource: "@WozbeAdminBundle/Controller/"
    type:     annotation

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /
    
wozbe_page:
    resource: "@WozbePageBundle/Controller/"
    type:     annotation

wozbe_blog:
    resource: "@WozbeBlogBundle/Controller/"
    type:     annotation
