security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    thomas: { password: %admin_password%, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        admin:
            pattern:    ^/admin
            logout:       true
            anonymous:    true
            http_basic:
                realm: "Secured Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
