<?php

namespace Wozbe\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends EntityRepository
{
    /**
     * @param string $name
     * @return \Wozbe\AdminBundle\Entity\Configuration
     */
    public function findOneByName($name)
    {
        return $this->findOneBy(array('name' => $name));
    }
}
